class AuditAction:

    LOGIN_SUCCESS = "LOGIN_SUCCESS"

    LOGIN_FAILED = "LOGIN_FAILED"

    LOGOUT = "LOGOUT"


    USER_CREATED = "USER_CREATED"

    USER_UPDATED = "USER_UPDATED"

    USER_DELETED = "USER_DELETED"

    ROLE_CHANGED = "ROLE_CHANGED"

    USER_ACTIVATED = "USER_ACTIVATED"

    USER_DEACTIVATED = "USER_DEACTIVATED"