# Generated by Django 6.0.7 on 2026-08-11 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendances_employe_993bac_idx',
            old_name='attendance__employe_08d913_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendances_date_234e8d_idx',
            old_name='attendance__date_61f2e1_idx',
        ),
        migrations.RenameIndex(
            model_name='attendance',
            new_name='attendances_status_dae783_idx',
            old_name='attendance__status_132c06_idx',
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='attendances',
        ),
    ]
