# Generated by Django 6.0.7 on 2026-08-12 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0003_leaverequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('is_optional', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'name'), name='unique_holiday_date_name')],
            },
        ),
    ]
