# Generated by Django 6.0.7 on 2026-08-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0004_holiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='day_type',
            field=models.CharField(choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day')], default='FULL_DAY', max_length=20),
        ),
    ]
