# Generated by Django 6.0.7 on 2026-08-12 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_leaverequest_day_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_days_notice', models.PositiveIntegerField(default=0)),
                ('max_consecutive_days', models.PositiveIntegerField(default=0)),
                ('allow_half_day', models.BooleanField(default=True)),
                ('allow_backdated', models.BooleanField(default=False)),
                ('requires_reason', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='leave.leavetype')),
            ],
            options={
                'db_table': 'leave_policies',
            },
        ),
    ]
